Feature/splash
Ignaherrero/Gamma pull request #11
Opened 2021-01-12 01:45 UTC by kira4489

Buenas noches hice un componente splash en la carpeta pages que tiene una imagen y un texto que dice adogtemos

hice una variable global en styled components para poder ponerle el color de fondo a la pagina y organizar para que me quedara centrado el texto y la imagen.

Pregunta:puse el styles.tsx en pages no sabia donde ponerlo antes lo tenia en una carpeta aparte ya me dicen ustedes donde dejarlo.

Mando foto de como me estaba quedando antes no me estaba quedando bien.y por eso puse la variable global 
![logomal](https://user-images.githubusercontent.com/50423635/104258578-d2283f00-544d-11eb-9b6c-38487ec063d5.JPG)

Pd:no me puten mucho gracias!!

2021-01-12 22:21 UTC, nykka requested changes
Genial @kira4489 ! Te agregué un par de comentarios :D

2021-01-12 22:21 UTC, nykka commented on src/pages/Styles.tsx
> +import styled, { createGlobalStyle } from "styled-components";
Fijate que algunas lineas tienen indentación diferente, habria que ajustar eso así queda todo prolijo

2021-01-12 22:21 UTC, nykka commented on src/pages/Splash.tsx
> +                <StyledImg src={Logo} />
No te olvides de agregar el `alt` con una descripción. Por ahora puede ser algo como "Logo de Adogtemos".

2021-01-12 22:21 UTC, nykka commented on src/pages/Splash.tsx
> +            <GlobalStyle />
No conocía lo de GlobalStyle! Personalmente no me convence pero podemos ver esto cuando tengamos más definido el diseño de la app.

2021-01-13 01:46 UTC, 9gustin reviewed
Agrego comentarios!

2021-01-13 01:46 UTC, 9gustin commented on src/pages/Styles.tsx
> + display: flex;
creo que esta bien, en mi caso usaria grid para definir un layout complejo(definiendo espacios) y flex para posicionar un elemento dentro de un contenedor

2021-01-13 01:46 UTC, 9gustin commented on src/pages/Styles.tsx
> + font-size: 25px;
la font-size se podria integrar al archivo de variables que va a ser mergeado en la rama de botones

2021-01-13 01:46 UTC, 9gustin commented on src/pages/Splash.tsx
> +                <StyledImg src={Logo} />
+1

2021-01-13 01:46 UTC, 9gustin commented on src/pages/Splash.tsx
> +            <GlobalStyle />
+1

2021-01-13 01:47 UTC, 9gustin commented
Otro comentario que veo ahora, no pondria esa imagen en la descripcion del PR, sino que pondria como esta ahora

2021-01-21 17:01 UTC, kira4489 commented on src/pages/Splash.tsx
> +            <div>
Si lo quito se me daña 
![fondo de adoptemos](https://user-images.githubusercontent.com/50423635/105384544-5ada7400-5be0-11eb-9599-d6ccd30296d8.JPG)

2021-01-26 22:31 UTC, 9gustin approved these changes

2021-01-27 22:12 UTC, nykka approved these changes

2021-01-27 22:52 UTC, merged