Feature de botones sociales
Ignaherrero/Gamma pull request #12
Opened 2021-01-12 16:20 UTC by Kerwin-Joel

Se crearon los botones de sociales de registro, en el componente puedes pasar el nombre de la red social (aunque por ahora solo se agregaron 3) y se agregará automaticamente, ademas no tiene limite de argumentos, es decir que puedes poner una o varias redes sociales.
<img width="215" alt="Screen Shot 2021-01-12 at 11 19 31" src="https://user-images.githubusercontent.com/31675409/104341679-0ccebd80-54c8-11eb-82ee-30412404207b.png">

2021-01-12 22:12 UTC, nykka requested changes
Muy bueno @Kerwin-Joel ! Te agregué algunos comentarios :)

2021-01-12 22:12 UTC, nykka commented on src/index.tsx
> +            buttonsName={["bxl-google", "bxl-facebook-circle", "bxl-twitter"]}
Creo que estaria bueno que venga de un json, con los links como te comenté más arriba.

2021-01-12 22:12 UTC, nykka commented on src/index.tsx
> +        <ButtonSocial
Esto deberia estar en el archivo App.tsx, ahi es donde vamos a renderizar los componentes.

2021-01-12 22:12 UTC, nykka commented on src/index.tsx
> +            text="O via social media"
No me queda claro para que sería este texto

2021-01-12 22:12 UTC, nykka commented on src/components/ButtonSocial/index.tsx
> +                                    <Twitter className={`bx ${button}`}></Twitter>
Cómo lo armaste queda un `li` dentro de un `a` dentro de un `li`, habría que repensar esto.
<img width="597" alt="Screen Shot 2021-01-12 at 19 09 45" src="https://user-images.githubusercontent.com/8450941/104380433-c306c700-5509-11eb-9426-34353a60b4af.png">

2021-01-12 22:12 UTC, nykka commented on package-lock.json
> +        "bindings": {
No entiendo porque hay cambios en este archivo jeje

2021-01-12 22:12 UTC, nykka commented on public/index.html
> +    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
Personalmente creo que evitaría usar una librería solo para mostrar iconos. Con descargar unos SVG debería bastar.

2021-01-12 23:09 UTC, Kerwin-Joel commented on src/components/ButtonSocial/index.tsx
> +interface Props {
genial, tienes razon

2021-01-13 01:59 UTC, 9gustin reviewed
Agrego comentarios mi querido kerwinsin

2021-01-13 01:59 UTC, 9gustin commented on src/components/ButtonSocial/index.tsx
> +export const ButtonSocial = (props: Props) => {
desestructuracion, mucho muy importante

2021-01-13 01:59 UTC, 9gustin commented on src/components/ButtonSocial/index.tsx
> +export const ButtonSocial = (props: Props) => {
creo que el componente deberia tener otro nombre, ya que es para el texto mas el listado de botones, como "SocialLogins"

2021-01-13 01:59 UTC, 9gustin commented on src/components/ButtonSocial/styles.tsx
> +const Facebook = styled.li`
estos colores los pondria en el archivo de variables

2021-01-13 01:59 UTC, 9gustin commented on src/index.tsx
> +            buttonsName={["bxl-google", "bxl-facebook-circle", "bxl-twitter"]}
+1

2021-01-13 01:59 UTC, 9gustin commented on src/components/ButtonSocial/index.tsx
> +        <Fragment>
los fragments se pueden usar como <></>, es mas sencillo

2021-01-13 23:09 UTC, Kerwin-Joel commented on src/components/ButtonSocial/index.tsx
> +        <Fragment>
Los fragment son mas cool >:v

2021-01-13 23:19 UTC, Kerwin-Joel commented on src/components/ButtonSocial/index.tsx
> +                        <ItemList key={index}>
yasta

2021-01-13 23:47 UTC, Kerwin-Joel commented on src/components/ButtonSocial/index.tsx
> +        <Fragment>
yala

2021-01-13 23:50 UTC, Kerwin-Joel commented on src/components/ButtonSocial/index.tsx
> +export const ButtonSocial = (props: Props) => {
yala

2021-01-19 20:28 UTC, Ignaherrero commented
Creo que es bueno usar el nav>ul>li>a

2021-01-19 22:04 UTC, kira4489 commented on src/components/ButtonSocial/styles.tsx
> +const Facebook = styled.li`
+1

2021-01-26 22:34 UTC, 9gustin approved these changes
riki

2021-01-27 12:41 UTC, nykka commented on public/index.html
> +    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
Si al final usaste SVGs, habría que elminar esta línea, no?

2021-01-27 12:41 UTC, nykka requested changes
Esta perfect! Te agregué un solo comment.

2021-01-27 22:51 UTC, Kerwin-Joel reviewed
borrado el link de los iconos que estaba en el index.html
también borrado el export que estaba de más

2021-01-27 23:02 UTC, nykka approved these changes

2021-01-30 14:16 UTC, merged