Feature/pantalla de inicio
Ignaherrero/Gamma pull request #16
Opened 2021-01-19 18:30 UTC by Ignaherrero

En esta pantalla hay un mensaje de bienvenida con una imagen que se puede pasar por props al igual que los textos que estan por debajo
Cada boton lleva diferentes rutas donde se va a conectar con los componentes de registrarse y de inicio de sesión

Saludos

2021-01-21 14:21 UTC, nykka requested changes
Está genial Nacho! Te dejé algunos comentarios 👯

2021-01-21 14:21 UTC, nykka commented on src/components/HomeScreen/index.tsx
> +            <Image src={"https://www.imagen.com"} alt={"imagen del perrx gatx"} />
Si es un string no es necesario poner las llaves

2021-01-21 14:21 UTC, nykka commented on src/components/HomeScreen/styles.tsx
> +import styled from "styled-components";
Para los Styled componentes acordate que quedamos en nombrarlos con la palabra Styled al inicio, así que quedaría StyledContainer, StyledImageResponsive, etc.

2021-01-21 14:21 UTC, nykka commented on src/components/HomeScreen/title.tsx
> +const Title = ({ title }: ITitle): ReactElement => {
No se si haría una interface si solo va a recibir un string. Yo pondría {title}: string y ahorraria varias lineas

2021-01-21 14:21 UTC, nykka commented on src/pages/Login.tsx
> +        <>
Me parece que no hay necesidad de agregar un Fragment acá. De hecho podrías armarlo mucho más sintetico haciendo un return implicito. Algo como `const Login = () => <LoginMain />;`

2021-01-21 14:21 UTC, nykka commented on src/components/HomeScreen/paragraph.tsx
> +const Paragraph = ({ text }: IParagraph): ReactElement => {
No se si haría una interface si solo va a recibir un string. Yo pondría {text}: string y ahorraria varias lineas

2021-01-21 14:21 UTC, nykka commented on src/components/HomeScreen/message.tsx
> +            <Title title={"hola"} />
Si es un string no es necesario poner las llaves

2021-01-21 14:21 UTC, nykka commented on src/components/HomeScreen/index.tsx
> +            <Acces />
Access va con dos s

2021-01-21 14:21 UTC, nykka commented on src/components/HomeScreen/image.tsx
> +    return <ImageResonsive src={src} alt={alt} />;
Aca también podrías hacer un return implícito

2021-01-26 22:44 UTC, 9gustin reviewed
Tambien otra cosa a revisar es que tenes varios componentes dentro de HomeScreen, creo que se podria hacer mas carpetas dentro de HomeScreen en caso de que sean componentes exlusivos de ese componente o sacarlos en mas carpetas, para respetar la estructura de archivos(https://github.com/Ignaherrero/Gamma/tree/develop#file-structure).

2021-01-26 22:44 UTC, 9gustin commented on src/components/HomeScreen/access.tsx
> +    /** @function this function go to /movil-auth/useId and here the users can loggin with its account*/
Estos comentarios no son necesarios

2021-01-26 22:44 UTC, 9gustin commented on src/components/HomeScreen/message.tsx
> +const Mess = (): ReactElement => {
El nombre de este componente  y el de Access  creo que no alcanzan a ser lo suficientemente descriptivos

2021-01-26 22:44 UTC, 9gustin commented on src/routes/AppRouter.tsx
> +import index from "../components/HomeScreen";
aca podes importar el componente al igual que el otro.
```suggestion
const HomeScreen= React.lazy(() => import("../components/HomeScreen"));
```

2021-02-04 16:59 UTC, 9gustin reviewed
Un par de comentarios, lo demas piola!

2021-02-04 16:59 UTC, 9gustin commented on src/components/HomeScreen/containerLoginSignUp.tsx
> +import React, { ReactElement } from "react";
Le cambiaria el nombre al archivo a ContainerLoginSignUp/index.tsx

2021-02-04 16:59 UTC, 9gustin commented on src/components/HomeScreen/containerWelcomeMessege.tsx
> +import React, { ReactElement } from "react";
same, ContainerWelcomeMessege/index.tsx

2021-02-04 17:22 UTC, kira4489 commented on src/components/HomeScreen/containerLoginSignUp.tsx
> +import React, { ReactElement } from "react";
@9gustin pero el nombre que decis no esta super largo yo lo pondria mas corto

2021-02-05 01:15 UTC, anaggithub commented on src/components/HomeScreen/containerLoginSignUp.tsx
> +import React, { ReactElement } from "react";
Por qué esto va en la carpeta Components, no iría en la carpeta pages?

2021-02-05 01:19 UTC, anaggithub commented on src/components/HomeScreen/containerLoginSignUp.tsx
> +import React, { ReactElement } from "react";
Yo esto lo pondría en la page Login
![image](https://user-images.githubusercontent.com/47753872/106976242-d6870580-6736-11eb-82a8-533f67cacfc8.png)

No es logica de un container, si no de la page login... y no sé si sacaría a componentes los divs quecontienen cosas,  los pondría directamente en la page login como StyledContainers o algo así digamos... 

Bah no sé qué dicen ustedes... :D

2021-02-05 01:24 UTC, anaggithub commented on src/components/HomeScreen/containerWelcomeMessege.tsx
> +import React, { ReactElement } from "react";
Creo q no hace falta sacar esto a un componente..  Los componentes no son cosas q se rehutilizan en algun lado? Esto es siomplemente un div que contiene cosas...  no tiene ni estilos, ni logica, nada....

2021-02-05 01:29 UTC, anaggithub requested changes

2021-02-05 01:29 UTC, anaggithub commented on src/components/HomeScreen/containerWelcomeMessege.tsx
> +export default Message;
Como mencioné en el otro comment, aca por ej creo q no hace falta sacar esto a un componente..  ¿Los componentes no son cosas q se reutilizan en algun lado? Esto es simplemente un div que contiene cosas...  no tiene ni estilos, ni tipos, ni logica, nada.... es solo un div.

2021-02-10 21:53 UTC, 9gustin approved these changes
Aprobadou!

2021-02-10 22:46 UTC, nykka approved these changes

2021-02-10 23:27 UTC, anaggithub approved these changes

2021-02-10 23:56 UTC, merged