Agrego pagina de autenticacion movil
Ignaherrero/Gamma pull request #18
Opened 2021-01-26 23:47 UTC by 9gustin

## Cambios
Agrego pagina de autenticacion movil
Agrego servicio para realizar la autenticacion con firebase
Agrego validacion con recaptcha de firebase

## Capturas

![image](https://user-images.githubusercontent.com/38046239/105920909-ee63d880-6016-11eb-997c-12d112cfcdd7.png)

![image](https://user-images.githubusercontent.com/38046239/105920933-f7ed4080-6016-11eb-8f20-3a5c5b346014.png)

## Tarjeta
[Pagina de validacion con numero de telefono](https://trello.com/c/n2GVyQKp/18-pagina-de-validacion-con-numero-de-telefono)

## TODO
Deje afuera de este PR lo visual y el manejo de errores, ambas por cuestiones de que vengo arrastrando esta tarjeta hace varias semanas y es un PR gigante, asi que corregi la estructura archivos y lo corte aqui. Con respecto a lo visual parece que sebas avanzo y ya hay un diseño yyy sobre el manejo de errores habria que informarle al usuario. Asi que estaria abriendo esas dos tarjetas.

2021-01-27 13:06 UTC, nykka requested changes

2021-01-27 13:06 UTC, nykka commented on src/components/MovilAuth/RequestNumber/index.tsx
> +    const submit = (event: React.FormEvent) => handleSubmit && handleSubmit(statePhoneNumber);
Lo mismo que el comentario sobre la función `change`.

2021-01-27 13:06 UTC, nykka commented on src/components/MovilAuth/ValidateNumber/index.tsx
> +    const submit = () => handleSubmit(code);
Por que no le pasas directamente `hanldeSubmit(code)` al componente StyledForm?

2021-01-27 13:06 UTC, nykka commented on src/components/MovilAuth/ValidateNumber/styles.ts
> +    button {
Esto es raro. Creo que le haría un styled component al boton directamente.

2021-01-27 13:06 UTC, nykka commented on src/pages/Home.tsx
> +const Home = (): JSX.Element => {
Acá se puede hacer un return implícito. Sería `const Home = (): JSX.Element => <div>Home</div>;`

2021-01-27 13:06 UTC, nykka commented on src/pages/Login.tsx
> +const Login = (): JSX.Element => {
Acá se puede hacer un return implícito también

2021-01-27 13:06 UTC, nykka commented on src/pages/MovilAuth/index.tsx
> +    const closeValidation = () => setValidating(false);
Aca lo mismo, porque no le pasas directamente `setValidating(false);`?

2021-01-30 19:23 UTC, Ignaherrero commented on src/components/MovilAuth/PhoneNumber/index.tsx
> +                masks={{ ar: "... ...-...." }}
Holaa Agus 
A las props escuche en un curso que recomiendan ordenarlas con la extención alphabetical sorter

2021-02-01 14:15 UTC, 9gustin commented on src/components/Form/index.tsx
> +}: iForm): JSX.Element => {
Sip, sino tira error, creo que es una validacion de ESLint que tiene activada

2021-02-01 15:21 UTC, 9gustin commented on src/components/MovilAuth/PhoneNumber/index.tsx
> +    const change = (value: string) => {
pa mi en ambos casos no esta mal, porque no es que le pasan el evento, sino que en el caso de este input le pasa el value y en el caso del RequestNumber/index.tsx cuando se submitea pasa el numero que esta en el state y no quedaria tan piola meterlo en el html como
`
onChange={(value: string) => handleChange?.(value);}
`
o 
`<Form handleSubmit={() => handleSubmit?.(statePhoneNumber);} isContentCentered>`

2021-02-01 15:21 UTC, 9gustin commented on src/components/MovilAuth/RequestNumber/index.tsx
> +    const submit = (event: React.FormEvent) => handleSubmit && handleSubmit(statePhoneNumber);
https://github.com/Ignaherrero/Gamma/pull/18#discussion_r567906227

2021-02-01 15:21 UTC, 9gustin commented on src/components/MovilAuth/ValidateNumber/index.tsx
> +    const submit = () => handleSubmit(code);
https://github.com/Ignaherrero/Gamma/pull/18#discussion_r567906227

2021-02-01 15:23 UTC, 9gustin commented on src/components/MovilAuth/PhoneNumber/index.tsx
> +                masks={{ ar: "... ...-...." }}
Resuelto en: https://github.com/Ignaherrero/Gamma/pull/19

2021-02-01 15:28 UTC, 9gustin commented on src/pages/Home.tsx
> +const Home = (): JSX.Element => {
Corregido

2021-02-01 15:28 UTC, 9gustin commented on src/pages/Login.tsx
> +const Login = (): JSX.Element => {
Corregido

2021-02-01 15:28 UTC, 9gustin commented on package.json
> +        "react-phone-number-input": "^3.1.8",
Corregido

2021-02-01 15:28 UTC, 9gustin commented on src/components/Form/styles.ts
> +export const StyledForm = styled.form`
Corregido

2021-02-10 16:23 UTC, Ignaherrero requested changes

2021-02-10 16:23 UTC, Ignaherrero commented on src/pages/MovilAuth/styles.ts
> +    align-self: flex-end;
align seft es una propiedad de flexbox, no es necesaria segun veo

2021-02-10 16:23 UTC, Ignaherrero commented on src/pages/MovilAuth/index.tsx
> +export default function index() {
no es mejor utilizar una declaración de funcion?
también vi que esta este warning Missing return type on function

2021-02-12 13:57 UTC, Ignaherrero reviewed
....

2021-02-12 13:57 UTC, Ignaherrero submitted a review, later dismissed

2021-03-08 00:00 UTC, nykka approved these changes
Genial Agus! Lo único, antes de mergear, fijate que algunas cosas están en `rem` y estamos usando `px`! 🎉

2021-03-09 00:30 UTC, anaggithub requested changes

2021-03-09 00:30 UTC, anaggithub commented on src/components/MovilAuth/CodeVerification/index.tsx
> +import React from "react";
Holi! Este componente Movil Auth es algo que va a ser utilizado unicamente en la page Movil Auth no? Entonces podríamos hacer como se hizo en la page ChooseProfile que todavía no está mergeada, link para q veas:
https://github.com/Ignaherrero/Gamma/pull/33/files

![image](https://user-images.githubusercontent.com/47753872/110399934-777a2080-8055-11eb-9668-62204ce74d17.png)

2021-03-22 14:39 UTC, Ignaherrero submitted a review, later dismissed

2021-03-28 17:52 UTC, AnibalDBXD approved these changes

2021-03-29 15:58 UTC, anaggithub approved these changes

2021-03-31 22:18 UTC, merged