Feature/estilos botones
Ignaherrero/Gamma pull request #21
Opened 2021-02-04 17:33 UTC by Ignaherrero

![imagen](https://user-images.githubusercontent.com/44342115/106931884-d4e91d80-66f5-11eb-88e0-ffa84d6305d8.png)

Agrego los estilos a los botones, hay dos botones, uno es el primario y el otro es el secundario (ghost)

2021-02-04 17:50 UTC, kira4489 commented
Este es mi primer pr para ti, no lo veo igual que al de figma, organizaría los colores y el hover

2021-02-04 22:51 UTC, anaggithub requested changes

2021-02-04 22:51 UTC, anaggithub commented on src/common/styles/index.tsx
> +    green: "#00A59E"
Como menciona Kira, los colores son diferentes! 
Si les haces click a los colores ene l figma, te muestra a la derecha cuál es cada uno. Ej:
![image](https://user-images.githubusercontent.com/47753872/106964366-c06e4a80-6720-11eb-912e-1186fdd80249.png)

2021-02-04 22:51 UTC, anaggithub commented on src/components/Button/styles.tsx
> +        color: ${theme.ghostButton};
Yo acá lo haría diferente. Colocaría el color verde, como colorSecondary.  Entonces este boton secondary tendría background-color: theme.white, y luego border y color: theme:colorSecondary.
No haría falta crear lo de ghostButton, y me parece que tiene más sentido así.
Bah, no sé qué opinan los demás?

2021-02-05 12:52 UTC, Ignaherrero commented on src/common/styles/index.tsx
> +    green: "#00A59E"
así?
![imagen](https://user-images.githubusercontent.com/44342115/107036034-c2272500-6797-11eb-9d7a-d0cd34f0b099.png)
![imagen](https://user-images.githubusercontent.com/44342115/107036043-c4897f00-6797-11eb-9f40-8f1ba5bb96ba.png)

2021-02-05 12:55 UTC, Ignaherrero commented on src/components/Button/styles.tsx
> +        color: ${theme.ghostButton};
me parece muy bueno, en el proximo commit subo esos cambios

2021-02-05 12:57 UTC, Ignaherrero commented
> 
> 
> Este es mi primer pr para ti, no lo veo igual que al de figma, organizaría los colores y el hover

En el proximo commit llevo al hover abajo

2021-02-06 04:04 UTC, kira4489 commented on src/common/styles/index.tsx
> +    green: "#00A59E"
Si esos son

2021-02-07 21:39 UTC, nykka commented on src/components/Button/styles.tsx
> +    width: 243px;
Creo que seria mejor usar min-width por si algun boton llega a necesitar mas espacio.

2021-02-07 22:12 UTC, anaggithub approved these changes

2021-02-09 23:18 UTC, Gus-Gonz approved these changes
Te dejo un comentario con mi review pero en general esta listo para ser utilizado 

Nota: si haces el merge después del de [ESTE PR](https://github.com/Ignaherrero/Gamma/pull/22) recuerda hacer un pull de develop y después el merge correspondiente en local, Hadita también modifico el archivo common/styles/index.tsx asi que te podría generar conflictos

2021-02-09 23:18 UTC, Gus-Gonz commented on src/components/Button/styles.tsx
> +    min-width: 243px;
Creo que el comentario de Nykka se refería a que agregaras un **min-width** a lo que ya tenias,

Borrar el **width** teniendo un **min-width** es un poco sin sentido ya que la idea es que tengamos un **width** dinámico pero con un mínimo en el tamaño.

2021-02-09 23:32 UTC, merged