Se creó el componente Input
Ignaherrero/Gamma pull request #22
Opened 2021-02-04 23:00 UTC by anaggithub

Descripción: Se creó un componente Input para poder utilizar en toda la app. Los screens los saqué antes de ponerle la font Poppins, que al final se la tuve que sacar para que no me diera error el linter y poder mandar el PR  que varios lo necesitan en sus tareas.

Nota: no sé si me puede haber faltado alguna prop importante al usar en los inputs, por favor me avisen si faltara alguna!!

Ejemplo de cómo se podría utilizar:
![image](https://user-images.githubusercontent.com/47753872/106965981-4095af80-6723-11eb-9ba0-4a6be692b330.png)

Cómo se vería el input sin ícono:
![image](https://user-images.githubusercontent.com/47753872/106965658-ae8da700-6722-11eb-8ffd-2216af2197f0.png)

Con ícono:
![image](https://user-images.githubusercontent.com/47753872/106965706-c533fe00-6722-11eb-95db-a71674043297.png)

2021-02-05 01:08 UTC, anaggithub commented on src/components/Input/index.tsx
> +const Input: React.FunctionComponent<IInput> = ({
Holi!! Pero pero hace falta? El value actual del input no estaría almacenado en los states del componente padre que llame al input? Como en el ej q dejé:
https://user-images.githubusercontent.com/47753872/106965981-4095af80-6723-11eb-9ba0-4a6be692b330.png

2021-02-05 01:12 UTC, anaggithub commented on src/common/styles/index.tsx
> +    font16: "16px"
Agregados!!

2021-02-06 01:06 UTC, Gus-Gonz commented on src/components/Input/index.tsx
> +const Input: React.FunctionComponent<IInput> = ({
Falta falta no hace en realidad , el Input funciona sin problemas sin que el padre le pase el value (que seria el state almacenado), solo es un capricho mio hahaha

2021-02-06 01:15 UTC, Gus-Gonz approved these changes

2021-02-06 03:36 UTC, kira4489 reviewed
No se lo apruebo porque no me puso como review

2021-02-06 15:09 UTC, Ignaherrero requested changes

2021-02-06 18:55 UTC, anaggithub commented on src/components/Input/styles.tsx
> +    :-webkit-autofill:active {
Cómo cómo? Quitarlos cómo? Son para sobreescribir unos estilos q agrega chrome..

2021-02-06 19:11 UTC, kira4489 commented on src/components/Input/styles.tsx
> +        -webkit-box-shadow: 0 0 0px 1000px ${colors.lightGray} inset !important;
+1

2021-02-06 21:26 UTC, Ignaherrero commented on src/components/Input/styles.tsx
> +    :-webkit-autofill:active {
![imagen](https://user-images.githubusercontent.com/44342115/107129996-5b456100-68a8-11eb-985d-6b2d5b0079c2.png)
La podes quitar con 
```
&:focus {
        outline: none;
    }
```
También se podria usar normalize.css y agregar en ese archivo esto
```
input[type="text"] {
        outline-style: none;
    }
```

2021-02-07 21:22 UTC, anaggithub commented on src/components/Input/styles.tsx
> +        -webkit-box-shadow: 0 0 0px 1000px ${colors.lightGray} inset !important;
Estos estilos para sobreescribir los estilos de google los googlié y pegué como los encontré , no saque el important porque pensé q había que ponerlo sí o sí para q funcionen, pero ahí probé quitarlo y anda igual! 
Commit pusheado!

2021-02-07 21:22 UTC, anaggithub commented on src/components/Input/index.tsx
> +const Input: React.FunctionComponent<IInput> = ({
Bueno podemos ver qué opinan los demás :D

2021-02-07 21:29 UTC, anaggithub commented on src/components/Input/styles.tsx
> +    :-webkit-autofill:active {
Yo tengo estos estilos:
![image](https://user-images.githubusercontent.com/47753872/107159902-b42cfc00-6971-11eb-9d25-c6cefff81b82.png)

que borran este color feo q agrega google al input:
![image](https://user-images.githubusercontent.com/47753872/107159934-ec343f00-6971-11eb-9ad9-946de17551fd.png)

Entendí que querés q los ponga así , pero así no funcionan..
![image](https://user-images.githubusercontent.com/47753872/107159964-1980ed00-6972-11eb-9645-27e462cb1b03.png)

Se sigue viendo ese color infiltrado y queda feaso. Capaz no te estoy entendiendo, pero si tenes un ratito, fetcheate la rama feature/input y probalo vos para q veass jeje

2021-02-08 15:42 UTC, Ignaherrero commented on src/components/Input/styles.tsx
> +    :-webkit-autofill:active {
Agrego como me quedo
![imagen](https://user-images.githubusercontent.com/44342115/107241577-e12ced80-6a09-11eb-8802-0344558b953c.png)

* Quizás sea porque te falta el &
* También se podria reemplazar el box-shadow por un background-color, tal vez no sea necesario usar el box-shadow (creo yo)
*

2021-02-08 15:43 UTC, Ignaherrero commented on src/components/Input/styles.tsx
> +    :-webkit-autofill:active {
El blue quedo de prueba  :sweat_smile:

2021-02-09 04:25 UTC, anaggithub commented on src/components/Input/styles.tsx
> +    :-webkit-autofill:active {
Mmm no me funciona  :(

Supongo que lo dejamos para el miércoles en la call porq creo q no da estar pasando capturas por acá de mis 200 intentos jajajaja.

2021-02-10 01:37 UTC, kira4489 approved these changes

2021-02-10 21:59 UTC, 9gustin reviewed
Comentarious

2021-02-10 21:59 UTC, 9gustin commented on src/components/Input/index.tsx
> +const Input: React.FunctionComponent<IInput> = ({
Me parece bien que reciba el value, para casos en donde el form es un valor precargado. Ademas agregaria la prop ref, por si queres tener la referencia del input en un padre.

2021-02-10 21:59 UTC, 9gustin commented on src/components/Input/styles.tsx
> +    :-webkit-autofill:active {
Me gusta la idea de agregar normalize o algo asi que resetee el css

2021-02-10 21:59 UTC, 9gustin commented on src/components/Input/types.ts
> +    id: string;
el id y el name pueden ser opcional

2021-02-10 22:23 UTC, Ignaherrero approved these changes

2021-02-10 22:35 UTC, merged