Feature/styles carousel component
Ignaherrero/Gamma pull request #24
Opened 2021-02-10 14:20 UTC by Gus-Gonz

![Preview](https://user-images.githubusercontent.com/64698390/107521137-f41dfa00-6b90-11eb-9ebb-bc2b51c89d1c.png)

Se cambio los estilos de los componentes dentro del Carousel , ademas se subió las imágenes correspondientes importadas de Figma como svg    

Debido a la forma en que React trata las imágenes , tuve que cambiar el Json que contenía la data del Carousel por un Archivo Jsx para poder, de manera dinámica; manejar el src de canda una de ella.

2021-02-10 19:21 UTC, Ignaherrero commented on src/components/Carousel/styles.tsx
>      list-style: none;
Esto creo que lo podrias llevar a StyleUl y tendría el mismo efecto
También se podría resetear los estilos body de las listas con esa propiedad, entonces no haría falta agregar en cada ul que se utilice en la app

2021-02-10 19:45 UTC, Ignaherrero commented on src/components/Carousel/styles.tsx
>      top: 0;
Esta propiedad entiendo yo se utiliza cuando tenemos position: relative, absolute o sticky. No veo que la estes usando en este comopnente o en el padre, me parece que no cumple ninguna funcion y se puede eliminar

2021-02-10 19:58 UTC, Ignaherrero commented on src/components/Carousel/styles.tsx
> +    max-height: 450px;
Aca veo que usas height y max-height, creo que con max-height es suficiente.
También usas 30rem y creo que es muy sercano a 450px (por eso el height esta demas), no lo pude probar en mi pc, esto se podría revisar

2021-02-10 19:59 UTC, Ignaherrero requested changes
Hice unos comentarios más que nada en css, creo que hay cosas que se podrían rever
También quiero agregar que me gusto mucho lo que hiciste, son unos detalles nomas esos comentarios que hoy lo podriamos ver

2021-02-10 23:18 UTC, Gus-Gonz commented on src/components/Carousel/styles.tsx
>      top: 0;
Ahora si usa position: absolute :v

2021-02-10 23:18 UTC, Gus-Gonz commented on src/components/Carousel/styles.tsx
> +    max-height: 450px;
ahora solo usa height

2021-02-11 01:19 UTC, Ignaherrero approved these changes

2021-02-11 02:19 UTC, 9gustin reviewed
Un par de comentarios, pero en general re bien!

2021-02-11 02:19 UTC, 9gustin commented on src/components/Carousel/DotsSlider/styles.tsx
> +    background-color: ${({ active }) => (active ? colors.orange : "#FFC7A3")};
Creo que el otro color deberia estar en el archivo de colores

2021-02-11 02:19 UTC, 9gustin commented on src/components/Carousel/styles.tsx
> +    @media (min-width: 400px) {
Se podria hacer un archivo con los breakpoints de los dispositivos

2021-02-11 15:27 UTC, Gus-Gonz commented on src/components/Carousel/DotsSlider/styles.tsx
> +    background-color: ${({ active }) => (active ? colors.orange : "#FFC7A3")};
Se agrego el color al achivo en common

2021-02-11 18:52 UTC, AnibalDBXD approved these changes
Bien ahi!

2021-02-12 11:39 UTC, merged