Feature/login page
Ignaherrero/Gamma pull request #28
Opened 2021-02-11 17:00 UTC by Gus-Gonz

**PREVIEW**
![PREVIEW](https://user-images.githubusercontent.com/64698390/107669186-3e29dd00-6c70-11eb-957f-0f623ada2cbe.gif)

Es una pagina para el login del usuario. Esta maneja estados guardando el value de los inputs y una validación , la cual sera utilizada al momento de hacer click en el boton para ingreasar para hacer el ajax correspondiente al servidor y autenticar al usuario o para indicarle que el password no posee el tamaño requerido  y/o el email no posee un formato esperado ( XXXXX @ XXX . XXX) 

Queda por definir que exactamente se hará al hacer click en el boton

2021-02-11 18:40 UTC, AnibalDBXD commented on src/pages/Login/index.tsx
> +            </Button>
Si pones el Button dentro del form hara que cuando le des enter al los inputs se ejecute la funcion del button

2021-02-11 18:40 UTC, AnibalDBXD commented on src/pages/Login/index.tsx
> +            <form onSubmit={(event) => event.preventDefault}>
Sin los () el event.preventDefault no se ejecuta!

2021-02-11 21:27 UTC, Ignaherrero commented on src/pages/Login/index.tsx
> +            </Button>
También se puede usar <input type="submit" value="Ingresar">

2021-02-12 11:36 UTC, Gus-Gonz commented on src/pages/Login/index.tsx
> +            <form onSubmit={(event) => event.preventDefault}>
Tienes toda la razón , ni me había dado cuenta que les faltaba

2021-02-12 11:38 UTC, Gus-Gonz commented on src/pages/Login/index.tsx
> +            </Button>
en este caso haré los que recomienda anibal , aunque es cierto que usar un input es posible tendría que crear el estilo de cero y dado que button ya los tiene pues ...

2021-02-12 11:43 UTC, Gus-Gonz commented
Modificaciones realizadas

2021-02-12 12:23 UTC, Ignaherrero approved these changes

2021-02-12 22:58 UTC, anaggithub commented on src/pages/Login/index.tsx
> +            </Button>
No sé si ya lo resolviste pero como dice Anibal , el button debería ir dentro del form. Entiendo que es una buena práctica poner dentro del tag form, todo lo que sea parte del formulario, inputs y botones. Incluso si es un form chiquito con un solo input y un boton o cosas así.. Bah eso me enseñaron en un curso jajaa :D

2021-02-12 23:03 UTC, anaggithub requested changes

2021-02-12 23:03 UTC, anaggithub commented on src/img/Logo-con-colores.svg
> +</svg>
Holii! Kira ya subió un logo a la app, el q está usando en la page Splash, son logos diferentes? Pareciera que es el mismo... pregunto x las dudas para no cargarlo dos veces en caso de que sea el mismo.

![image](https://user-images.githubusercontent.com/47753872/107831588-284e1200-6d6d-11eb-9a87-9f00c9cb2b5f.png)

![image](https://user-images.githubusercontent.com/47753872/107831648-4ca9ee80-6d6d-11eb-9278-b88dff42764d.png)

2021-02-12 23:21 UTC, anaggithub requested changes

2021-02-12 23:21 UTC, anaggithub commented on src/pages/Login/index.tsx
> +    });
No sé qué opinen los demás pero acá los nombres de los states están medio largos y creo que se podría optar por nombres más breves y claros, por ej. podrían ser _username_ y _password_, o incluso _name_ y passoword, entendiéndose que es el nombre de la cuenta. 
Ej: 
```
const [username, setUsername] 
const [password, setPassword]
```

Qué les parece?

2021-02-12 23:21 UTC, anaggithub commented on src/pages/Login/index.tsx
> +export default LoginPage;
Sólo quería decir que me encanta esta page!! Todo en el index bien acomodado y no sacado fuera de otros archivos innecesariamente jajjaj. Bueno son gustos igual pero gueno, así me gusta a míi jajaja :D

2021-02-12 23:21 UTC, anaggithub commented on src/pages/Login/styles.tsx
> +    font-family: ${fonts.roboto};
Acá un detalle, la fuente no es Roboto, es Poppins. Si tenés ganitas agregala así ya nos queda. Tendrías que ponerla en el archivo common styles,  dentro del objeto "fonts", y luego como "font primary", para así se aplique directamente en los demás componentes q llaman a la font primary.

![image](https://user-images.githubusercontent.com/47753872/107832481-49176700-6d6f-11eb-9279-e984c4f310eb.png)

2021-02-12 23:40 UTC, Gus-Gonz commented on src/pages/Login/index.tsx
> +            </Button>
Si ya esta resuelto

2021-02-12 23:49 UTC, 9gustin commented on src/pages/Login/index.tsx
> +    });
me gusta, pero ademas solo tendria un estado que sea el usuario, agregaria la interfaz del usuario yyyy la validacion la podria en una funcion aparte, que puede ser un util

2021-02-12 23:49 UTC, 9gustin commented on src/pages/Login/index.tsx
> +    const AccountInputHandler = (event: React.ChangeEvent<HTMLInputElement>) => {
Yo usaria solo un event handler y tomaria el campo name/id del input para determinar que propiedad es

2021-02-12 23:49 UTC, 9gustin commented on src/pages/Login/index.tsx
> +                <Button onClick={() => loginButtonClicked()} variant={"primary"}>
aca quedaria mejor manejarlo en el submit, que el boton solo sea un boton de tipo submit y haya un evento que controle el submit del form y ejecute loginButtonClicked

2021-02-12 23:49 UTC, 9gustin commented on src/pages/Login/index.tsx
> +export default LoginPage;
jasdjajsdjas

2021-02-12 23:49 UTC, 9gustin commented on src/pages/Login/utils.tsx
> +        const redgex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
```suggestion
        const regexp= /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
```

2021-02-13 12:36 UTC, Gus-Gonz commented on src/img/Logo-con-colores.svg
> +</svg>
Gracias por recordármelo , Solucionado !!

2021-02-13 13:18 UTC, Gus-Gonz commented on src/pages/Login/index.tsx
> +    });
Se redujo los nombres de los estados a : 

`
const [usernameObj, setUsernameObj]
const [passwordObj, setPasswordObj]
`

2021-02-13 13:19 UTC, Gus-Gonz commented on src/pages/Login/utils.tsx
> +        const redgex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
Gracias por hacérmelo notar

2021-02-13 13:40 UTC, Gus-Gonz commented on src/pages/Login/styles.tsx
> +    font-family: ${fonts.roboto};
Listo , Poppins lo agregue como fontPrimary

2021-02-13 13:41 UTC, Gus-Gonz commented
Cambios realizados según lo solicitado y que considere pertinente

2021-02-16 23:25 UTC, nykka requested changes
Está muy bueno Gus!!! 👯 
Te dejé unos comentarios, cualquier cosa lo charlamos en Discord.

2021-02-16 23:25 UTC, nykka commented on src/pages/Login/index.tsx
> +            <form onSubmit={(event) => event.preventDefault()}>
Según lo que habíamos hablado en Discord, habria que pasar una referencia a la función en vez de la función directamente.
`const fnCopada = () => { //...// };
 <Component onSubmit={fnCopada}>`

2021-02-16 23:25 UTC, nykka commented on src/pages/Login/index.tsx
> +                <Button onClick={() => loginButtonClicked()} variant={"primary"}>
`onClick` se tiene que aplicar al elemento que va efectivamente va a recibir el click, no al componente. Cómo acá lo que estás haciendo es pasar la función como prop, sería mejor llamaría de otra forma. Podría ser handleClick quedándote handleClick={handleClick}

2021-02-16 23:25 UTC, nykka commented on src/pages/Login/index.tsx
> +            console.log("clicked!!! El usuario y la Contraseña SON validos");
In English!!! XD

2021-02-16 23:25 UTC, nykka commented on src/pages/Login/index.tsx
> +            return console.log("clicked!! El usuario o la Contraseña NO ES valida");
In English!!! :p

2021-02-16 23:25 UTC, nykka commented on src/pages/Login/index.tsx
> +            valid: InputIsValid(newValue)
Creo que seria mejor guadar el resultado de `InputIsValid` en una variable y pasarle esa variable, en vez de la función. Algo como:
`const isValid = InputIsValid(newValue);`
`const newState = {
            ...passwordObj,
            value: newValue,
            valid: isValid
};`

2021-02-16 23:25 UTC, nykka commented on src/pages/Login/index.tsx
> +            valid: InputIsValid(newValue, true)
Lo mismo que te comenté abajo :p

2021-02-18 00:33 UTC, anaggithub commented on src/pages/Login/index.tsx
> +import Button from "../../components/Button/index";
Holi! No hace falta importar el index! 

```suggestion
import Button from "../../components/Button";
```
```suggestion
import Button from "../../components/Button/index";
```

2021-02-19 14:54 UTC, Gus-Gonz commented on src/pages/Login/index.tsx
> +import Button from "../../components/Button/index";
Se cambio como solicitado

2021-02-24 23:07 UTC, 9gustin commented
![](https://cdn.discordapp.com/attachments/772238281755590686/814271270233047070/unknown.png)

2021-02-25 15:45 UTC, nykka approved these changes
Aprobadísimo

2021-02-25 15:59 UTC, Ignaherrero approved these changes

2021-02-25 16:05 UTC, anaggithub approved these changes

2021-02-25 18:38 UTC, merged