Estilos, Logica de pulsar los Roles, Extender el componente Button.
Ignaherrero/Gamma pull request #33
Opened 2021-02-13 22:17 UTC by AnibalDBXD

2021-02-14 22:02 UTC, anaggithub reviewed
Holi! Podrías poner una captura de la page acá en la descripción? Y una breve descripción también, yo también a veces me olvido! Jajaja :D

2021-02-14 22:02 UTC, anaggithub commented on src/components/Button/index.tsx
> +    disabled
Disabled le podríamos poner que esté siempre false por defecto? Qué les parece?

2021-02-14 22:15 UTC, anaggithub commented on src/pages/ChooseProfile/index.tsx
> +        <Container>
Otra cosita! Según recuerdo habíamos decidido que cuando son Styled Components, usar de nombre "StyledLoQueSea". Podes verlo en los componentes: Button, ButtonSocial, Carousel, Image, etc. Te dejo un ej :
![image](https://user-images.githubusercontent.com/47753872/107890628-b0acee00-6ef8-11eb-9bc2-0c123488e47b.png)

Es algo que facilita mucho la lectura y por eso decidimos usarlo! Si hay alguna parte en la app que le falta es porque fue de antes de esta decisión y deberíamos modificarlo.

2021-02-14 22:21 UTC, anaggithub commented on src/components/ProfileRoleContainer/index.tsx
> +import React, { useState } from "react";
Holi! Esto es parecido a lo que charlamos anteriormente en un pr de nacho... Él había sacado fuera partes de la page HomeScreen y las había mandado a la carpeta components, y luego en la call charlamos de que esos eran simplemente divs contenedores necesarios en esa page puntual, pero no eran componentes q fueran a ser reutilizados en las demás pages de la app. Creo que acá está pasando lo mismo. 

Si realmente necesitas sacar fuera código para facilitar la lectura y no nos quede el index de la page con 300 lineas, podríamos sacarlo afuera pero colocarlo en la misma subcarpeta dentro de pages, y no en la carpeta Components. Insisto que components son cosas a reutilizar. 

Qué opinan los demás de esto? Quedaría algo así: 
![image](https://user-images.githubusercontent.com/47753872/107890809-a7705100-6ef9-11eb-8a97-3f49740d9f90.png)

2021-02-15 19:13 UTC, AnibalDBXD commented on src/components/Button/index.tsx
> +    disabled
Me parece buena idea tenerlo por defecto en false.

2021-02-15 19:13 UTC, AnibalDBXD commented on src/components/ProfileRoleContainer/index.tsx
> +import React, { useState } from "react";
Corregido

2021-02-15 19:13 UTC, AnibalDBXD commented
Cambios realizados.

Vista desktop
![desktop](https://user-images.githubusercontent.com/66853369/107985362-56676800-6fa0-11eb-84c4-860f5e1d1c27.gif)

Vista Mobile
![mobile](https://user-images.githubusercontent.com/66853369/107985376-5ebfa300-6fa0-11eb-8c85-319d94369ea3.gif)

2021-02-15 19:14 UTC, AnibalDBXD commented on src/pages/ChooseProfile/index.tsx
> +        <Container>
Corregido!

2021-02-16 02:53 UTC, anaggithub approved these changes
Aprobadisimo!

2021-02-16 22:49 UTC, nykka requested changes
Buenísimo Anibal!!! 
Te dejé unos comentarios!

2021-02-16 22:49 UTC, nykka commented on src/components/Button/index.tsx
> +const Button: React.FunctionComponent<IButton> = ({
Le hice un comentario a Hadita en su PR sobre usar `FC` en vez de `FunctionComponent`. Pero voy a dejar un mensaje en el canal de Discord así lo discutimos entre todxs.

2021-02-16 22:49 UTC, nykka commented on src/pages/ChooseProfile/ProfileRoleContainer/ProfileRole/index.tsx
> +            onClick={handleClick}>
`onClick` se tiene que aplicar al elemento que va efectivamente va a recibir el click, en este caso el botón (no el div). Cómo acá solo le estás pasando la función como prop, me parece que sería mejor llamaría de otra forma. Podría ser `handleClick` quedándote `handleClick={handleClick}`

2021-02-16 22:49 UTC, nykka commented on src/pages/ChooseProfile/ProfileRoleContainer/ProfileRole/styles.tsx
> +export const StyledProfileRole = styled.div`
Acá creo que deberias tipar que va a recibir color como parámetro.
`export const StyledProfileRole = styled.div<{ color?: string }>``

2021-02-16 22:49 UTC, nykka commented on src/pages/ChooseProfile/ProfileRoleContainer/index.tsx
> +const ProfileRoleContainer: React.FC = (): JSX.Element => {
Recién veo que acá usas `FC`. Deberíamos ponernos de acuerdo para usar lo mismo en todos los archivos.

2021-02-16 22:49 UTC, nykka commented on src/pages/ChooseProfile/ProfileRoleContainer/index.tsx
> +                        onClick={() => handleClick(id, path)}
Acá pasa lo mismo que te comenté sobre el `onClick`

2021-02-17 16:06 UTC, 9gustin requested changes

2021-02-17 16:06 UTC, 9gustin commented on src/pages/ChooseProfile/ProfileRoleContainer/ProfileRole/index.tsx
> +        if (selected === id) {
aca no haria falta usar el const [Active, setActive] = useState(false) , esta comparacion deberia estar en el padre y el hijo solo deberia recibir el booleano si esta seleccionado o no

2021-02-17 16:06 UTC, 9gustin commented on src/pages/ChooseProfile/ProfileRoleContainer/index.tsx
> +                        selected={Selected?.id || null}
```suggestion
                        selected={Selected?.id === id}
```

2021-02-17 16:06 UTC, 9gustin commented on src/pages/ChooseProfile/ProfileRoleContainer/ProfileRole/types.ts
> +    selected: string | null;
```suggestion
    selected: boolean|null;
```

2021-02-17 21:39 UTC, 9gustin submitted a review, later dismissed
:D

2021-02-19 13:45 UTC, 9gustin approved these changes
:D x2

2021-02-25 15:44 UTC, nykka approved these changes
Aprobadísimo!

2021-03-07 23:56 UTC, nykka requested changes
Esta muy bueno Anibal! Te deje unos comentarios de unos detalles nomás 🎉

2021-03-07 23:56 UTC, nykka commented on src/pages/ChooseProfile/ProfileRoleContainer/index.tsx
> +    const [BotonDisabled, setBotonDisabled] = useState(true);
`ButtonDisabled` y `setButtonDisabled`

2021-03-07 23:56 UTC, nykka commented on src/pages/ChooseProfile/ProfileRoleContainer/index.tsx
> +                handleClick={(): void => console.log(Selected)}
Yo evitaria dejar console.logs. Mejor que por ahora no haga nada y le agregamos el handleClick cuando tengamos la funcionalidad lista.

2021-03-07 23:56 UTC, nykka commented on src/pages/ChooseProfile/ProfileRoleContainer/rolesData.json
> +        "id": "orange",
No me convence que el ID sea un color, debería ser algo descriptivo del objeto.

2021-03-07 23:56 UTC, nykka commented on src/pages/ChooseProfile/styles.tsx
> +    padding: 1rem;
Por ahora vamos a usar pixeles en vez de rem.

2021-03-08 15:46 UTC, anaggithub commented on src/pages/ChooseProfile/ProfileRoleContainer/styles.tsx
> +    &.disabled {
Holi!!! Los estilos de si el botón está deshabilitado o no, me parece que deberían ir al componente button en sí mismo, si no tocaría agregarlos en cualquier parte de la app donde queramos deshabilitarlos y tendríamos código repetido! Qué piensan los demás?

2021-03-08 15:46 UTC, anaggithub commented on src/routes/paths.ts
>      Splash = "/Splash",
Holi! Si queres ya q estás, pone el splash en minuscula? así como están los demas . Sería "/splash", en la linea2 :D

2021-03-08 15:46 UTC, anaggithub commented on src/pages/ChooseProfile/styles.tsx
> +        font-size: ${fontSizes.font30};
Holi! Según yo, no tenemos diseños ni tamaños para lo que es responsive... Estos font sizes los elegiste vos al azar digamos o se decidió en alguna de las reuniones que me perdí? Yo tenía entendido que estamos haciendo el diseño mobile por defecto porque las pantallas son mobile, fijate que ninguno de los demás componentes tienen media queries ni nada.
Me avisen porfi si es algo que se decidió y yo no me enteré !

2021-03-09 00:07 UTC, 9gustin commented on src/pages/ChooseProfile/ProfileRoleContainer/rolesData.json
> +        "id": "orange",
Esta info quizas en un futuro puede estar en la BD, como ser los roles, son ids random, pero ahi los hice mas random xd

2021-03-09 00:14 UTC, 9gustin commented on src/routes/paths.ts
>      Splash = "/Splash",
noooooo, el ya que estamos es lo peor que puede hacer un programador (?)

2021-03-09 00:15 UTC, 9gustin commented on src/pages/ChooseProfile/styles.tsx
> +        font-size: ${fontSizes.font30};
kksadkkasd si a todo, lo hice porque quedaba feo en desktop y no me costaba nada hacerlo un toquesin mas lindo, se pueden cambiar los tamaños y lo que sea despues en las variables

2021-03-09 00:20 UTC, anaggithub commented on src/pages/ChooseProfile/styles.tsx
> +        font-size: ${fontSizes.font30};
Po qué respondes tu, este pr no es de anibal? jajajaja dejen de hacer esoo, se portan muy mal jajajaja

2021-03-29 16:03 UTC, anaggithub commented on src/pages/ChooseProfile/ProfileRoleContainer/index.tsx
> +    const [ButtonDisabled, setButtonDisabled] = useState(true);
Holi! No es convención poner los states en camelCase?

2021-04-01 15:37 UTC, 9gustin commented on src/pages/ChooseProfile/ProfileRoleContainer/index.tsx
> +    const [ButtonDisabled, setButtonDisabled] = useState(true);
listouuu

2021-04-09 13:33 UTC, Ignaherrero commented on src/common/styles/variables.tsx
> +//breakpoints
Puede ser que esto no este definido por ahora? No me acuerdo que hayamos hablado de los diferentes tamaños de pantalla

2021-04-14 22:36 UTC, nykka approved these changes

2021-04-14 22:36 UTC, anaggithub submitted a review, later dismissed

2021-04-14 22:41 UTC, nykka approved these changes

2021-04-14 22:42 UTC, anaggithub approved these changes

2021-04-14 22:42 UTC, merged