Feature/register
Ignaherrero/Gamma pull request #35
Opened 2021-02-17 00:24 UTC by kira4489

Buenas noches monto mi PR la pantalla de registro lo hice como lo entendi ya me dicen si esta bien asi o ahi que cambiar algo

saludos

![FOTO](https://user-images.githubusercontent.com/50423635/108135132-8d637980-7085-11eb-9260-f220410e871a.JPG)

2021-02-17 15:44 UTC, 9gustin reviewed
Un par de comentarios, lo demas se ve bien, no se si esta incluido agregarle las validaciones como hizo @Gus-Gonz con la pagina de login o solo era el maquetado

2021-02-17 15:44 UTC, 9gustin commented on src/components/Register/index.tsx
> +                <StyledTitle>Registrarse</StyledTitle>
```suggestion
                <StyledTitle>Registrate</StyledTitle>
```

2021-02-17 15:44 UTC, 9gustin commented on src/components/Register/styles.tsx
> +    background-color: #ff7b28;
Aca hay un color, creo que deberia ir al archivo de colores

2021-02-17 16:57 UTC, kira4489 commented on src/components/Register/index.tsx
> +                <StyledTitle>Registrarse</StyledTitle>
yo lo entendi que era el maquetafo

2021-02-17 17:05 UTC, 9gustin submitted a review, later dismissed
:D

2021-02-17 19:50 UTC, Ignaherrero commented
Los estilos no coinciden con los que estan en figma

2021-02-18 19:07 UTC, nykka requested changes
Va muy buen Kira! Faltaria usar los componentes que ya hay.

2021-02-25 16:08 UTC, anaggithub requested changes

2021-02-25 16:08 UTC, anaggithub commented on .eslintrc.js
> +        "prettier/prettier": ["error", {}, { usePrettierrc: true }], // Use our .prettierrc file as source
Hola! No sé qué pasó en esta branch pero están siendo comiteados archivos de otros PRs diferentes a este! Ni idea como solucionarlo, lo único que se me ocurre es cerrar este PR y que abras uno nuevo? No sé qué dicen los demás. 

Si miran los commits hay commits mios y de agustin tambien, diosito sabrá por qué!

Y acá en files changed hay como 10 files que son las modificaciones y correciones que yo hice en mi ultimo pr del linter, eso ya está comiteado y mergeado en develop, no debería aparecer acá de nuevo... o estoy confundida?

2021-02-25 16:10 UTC, anaggithub commented on src/components/Register/styles.tsx
> +    background-color: #ff7b28;
Sip los colores se están definiendo en common/styles si mal no recuerdo.

2021-02-25 22:21 UTC, closed without merging