Feature/nav
Ignaherrero/Gamma pull request #47
Opened 2021-03-12 19:17 UTC by Ceyene

![loquevaquedando](https://user-images.githubusercontent.com/56238760/110986936-1b611600-834d-11eb-8dec-0dcd38a05eb4.jpg)

Creado el componente Nav, junto con sus estilos.
Añadido el archivo i18n.ts con las traducciones de alt de cada ícono.
Había colocado el estado para apertura del menú pero lo removí para que eso sea agregado después en el layout.
(Usé la página NotFound para ir visualizando cómo quedaba, a modo de prueba, no lo incluyo en estos cambios).

2021-03-12 21:33 UTC, anaggithub commented on src/components/Nav/index.tsx
> +            <Link to="/">
Holi! Con respecto a los links, no es que estén mal pero tengo entendido que es mejor usar history push. Fijate que en home gus lo usò, te animàs a usarlo tambièn?
![image](https://user-images.githubusercontent.com/47753872/111000782-70a72280-8361-11eb-807c-e5982c70b5b8.png)

2021-03-12 21:37 UTC, anaggithub commented on src/components/Nav/index.tsx
> +            <Link to="/">
Tambien, las url no deberían estar en duro ahí me parece, deberían ser importadas desde Paths, se nos pasó decirle a gus ahora q veoo. 
![image](https://user-images.githubusercontent.com/47753872/111001052-ddbab800-8361-11eb-9a5b-b24aa0c6da03.png)

En path tenemos las rutas: 
![image](https://user-images.githubusercontent.com/47753872/111000973-c380da00-8361-11eb-935d-67eeb3e5acbc.png)

Vos estás mandando a "/", esa ruta habría que agregarla en paths, e importarla desde allí. Qué piensan los demás?

2021-03-12 23:23 UTC, Ceyene commented on src/components/Nav/index.tsx
> +            <Link to="/">
Buenísimo, voy a usarlo entonces.

2021-03-13 00:01 UTC, 9gustin submitted a review, later dismissed
😀 ✅

2021-03-13 00:01 UTC, 9gustin commented on src/components/Nav/index.tsx
> +            <Link to="/">
Pa mi el link esta bien, yo usaria history push cuando quiera pasar un state, en casos de solo redireccion pa mi ta bien asi noma

2021-03-13 21:22 UTC, AnibalDBXD requested changes
Al iniciar el proyecto me sale este error!

![image](https://user-images.githubusercontent.com/66853369/111044678-6566fc00-8420-11eb-9674-b863764ef325.png)

Ya que moviste el logo la solucion seria cambiar la ruta del logo en Home , Login , y Splash que son los archivos que lo utilizan.

Antes:
![image](https://user-images.githubusercontent.com/66853369/111044722-a4954d00-8420-11eb-8725-36772fc8b2d0.png)

Despues:
![image](https://user-images.githubusercontent.com/66853369/111044732-b1b23c00-8420-11eb-832a-41088ca3ba4d.png)

2021-03-14 20:41 UTC, Ceyene commented
Es cierto, ahora lo arreglo :D

2021-03-14 20:42 UTC, Ceyene commented on src/components/Nav/index.tsx
> +            <Link to="/">
Ustedes avisen si corresponde, no hay drama. Con respecto a las rutas, ¿debería crear la de messages?

2021-03-15 21:51 UTC, 9gustin approved these changes

2021-03-15 22:13 UTC, AnibalDBXD approved these changes

2021-03-15 23:24 UTC, merged