Br delete files
Ignaherrero/Gamma pull request #5
Opened 2021-01-05 22:59 UTC by Kerwin-Joel

Elimine archivos que create-react-app genera por defecto

2021-01-06 01:14 UTC, 9gustin reviewed
El PR esta apuntando a main y hay cosas de develop D:

2021-01-06 23:04 UTC, 9gustin requested changes
Apuntar el PR a la rama develop

2021-01-06 23:04 UTC, 9gustin commented on .eslintcache
> +[{"/Users/kerwinjoel/Desktop/Gamma/src/index.tsx":"1","/Users/kerwinjoel/Desktop/Gamma/src/routes/AppRouter.tsx":"2","/Users/kerwinjoel/Desktop/Gamma/src/routes/PrivateRoute.tsx":"3","/Users/kerwinjo
ESto no me gusta

2021-01-06 23:05 UTC, kira4489 reviewed
le falta mas añadir en el readme falta ser mas descriptivo no aprobado

2021-01-07 14:51 UTC, 9gustin approved these changes

2021-01-08 15:10 UTC, nykka commented
> le falta mas añadir en el readme falta ser mas descriptivo no aprobado

@kira4489 El readme va a ser parte de otra tarea, y otro PR

2021-01-08 15:11 UTC, nykka approved these changes

2021-01-12 04:20 UTC, Ignaherrero approved these changes

2021-01-13 17:45 UTC, closed without merging