Feature/componente mensaje
Ignaherrero/Gamma pull request #50
Opened 2021-03-18 23:07 UTC by AnibalDBXD

![component](https://user-images.githubusercontent.com/66853369/111708967-2c15fe00-881d-11eb-8047-5fad71034c9c.JPG)
![pixelperfect](https://user-images.githubusercontent.com/66853369/111708973-2e785800-881d-11eb-8a2f-cb70c55add8c.JPG)

2021-03-19 13:04 UTC, Gus-Gonz reviewed
Hola Anibal Excelente componente amigo <3 , te dejo unas cositas que podrías considerar , cualquier cosa la consultas en el grupo de gamma y se hablan con el equipo

2021-03-19 13:04 UTC, Gus-Gonz commented on src/components/Message/styles.tsx
> +    font-family: ${fonts.poppins};
No hay problemas con como implementaste en font aunque dentro del mismo archivo ../../common/styles tenemos una const theme que tiene dentro de ella "fontPrimary: fonts.poppins", considero seria mejor usar el theme así en caso de mas adelante cambiar la font no tengamos que revisar cada archivo de estilos en la app

`font-family: ${theme.fontPrimary};`

2021-03-19 13:04 UTC, Gus-Gonz commented on src/components/Message/styles.tsx
> +
los colores green y white también estan dentro de la const theme

2021-03-19 23:21 UTC, 9gustin commented on src/common/styles/index.tsx
> +    font11: "11px",
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm

2021-03-19 23:21 UTC, 9gustin commented on src/components/Message/index.tsx
> +    timeago,
mmmmm el mensaje tiene la fecha de creacion, esto deberia recibirla y usar un util para parsearla

2021-03-19 23:21 UTC, 9gustin commented on src/components/Message/index.tsx
> +    numberofmessage,
yo reemplazaria por algo mas como count o quantity

2021-03-19 23:21 UTC, 9gustin commented on src/components/Message/index.tsx
> +    isread,
```suggestion
    isRead,
```

2021-03-19 23:21 UTC, 9gustin commented on src/components/Message/index.tsx
> +                <StyledTimeAgo className={`${!isread && "isRead"}`}>{timeago}</StyledTimeAgo>
no entendi, si no esta leido le pones la clase "esta leido"? 👀

2021-03-19 23:21 UTC, 9gustin commented on src/components/Message/styles.tsx
> +    font-weight: 400;
pero si este weight es el normal, quizas se puede quitar esta linea 👀

2021-03-19 23:21 UTC, 9gustin commented on src/components/Message/styles.tsx
> +        props.className === "isRead" ? theme.colorSecondary : colors.gray};
aca deberias usar sass, algo como &.isRead {} o sino creo que es mejor usar una prop boolean, tipo que el padre reciba isRead y lo pase directamente a este componente

2021-03-19 23:21 UTC, 9gustin commented on src/components/Message/styles.tsx
> +    border-radius: 999px;
👀 esto es para que sea redondo? quizas anda un 100%, queda raro 999

2021-03-19 23:21 UTC, 9gustin commented on src/components/Message/types.ts
> +    src?: string;
quizas deberia tener un nombre mas descriptivo como profileIcon

2021-03-23 23:09 UTC, 9gustin approved these changes
Resolviste todo lo que te marque en un solo commit, hubiera quedado mas lindo separado, pero aprobado! :D

2021-03-24 01:42 UTC, anaggithub commented on src/components/Message/styles.tsx
> +
Por qué estas lineas en blanco?

2021-03-24 22:58 UTC, 9gustin requested changes

2021-03-24 22:58 UTC, 9gustin commented on package.json
> +        "dayjs": "^1.10.4",
usar moment, es mas copada (?

2021-03-26 19:25 UTC, 9gustin approved these changes

2021-03-31 18:30 UTC, Ignaherrero submitted a review, later dismissed

2021-04-04 14:15 UTC, 9gustin approved these changes

2021-04-07 22:58 UTC, anaggithub approved these changes

2021-04-07 22:58 UTC, merged